### ISSUE TITLE
Purchase Request

### ISSUE THREAD

**Issue by briansw** [artsy/force#261]
Related issue specific to the AB test: https://github.com/artsy/force/issues/434

This test affects artworks that are for sale and have an exact price listed. We'll test the feature with a select group of partners at first (list of partners still in progress).

Related MG issue: https://github.com/artsy/microgravity/issues/44
#### Todos
- [x] Change the name of ecommerce artwork "Buy" buttons to "Purchase"
- [x] Artwork page template updates
- [x] Checkout page
- [x] Confirmation page
- [x] Formatting of message field
- ~Add 'attending fair' checkbox~ Moved to new issue https://github.com/artsy/force/issues/464
- ~Create account fields~ moving to new issue: https://github.com/artsy/force/issues/448

#### Artwork page template
![force-artwork-template](https://cloud.githubusercontent.com/assets/1022172/19248692/83b0d750-8eff-11e6-9bd7-1cab0ca19e5f.jpg)

#### Responsive checkout page

![checkout](https://cloud.githubusercontent.com/assets/1022172/19519492/3cf36c6a-95da-11e6-8cf1-fd0705bc67b7.jpg)
#### Responsive payoff page

![payoff](https://cloud.githubusercontent.com/assets/1022172/19519525/62b261b8-95da-11e6-99d3-4b6c07dd9181.jpg)
#### Formatting of message field

![email](https://cloud.githubusercontent.com/assets/1022172/19573913/1b80483a-96d6-11e6-8ecf-824d62fd870d.jpg)

**Comment by rehat101** [comment]
@briansw which tool did you use to annotate these screens?

**Comment by briansw** [comment]
@rehat101 sketch

**Comment by rehat101** [comment]
A plugin or did you manually drew those?

**Comment by briansw** [comment]
@rehat101 manually in sketch

**Comment by briansw** [comment]
@1aurabrown when a work is in a fair, let's add the checkbox to the second page under the message field: https://cl.ly/2K1n2p1d1u0t

**Comment by briansw** [comment]
@1aurabrown as discussed, we're going to roll this out for all works with exact price that are available for purchase. cc @anipetrov

**Comment by briansw** [comment]
@1aurabrown here are the icons: http://files.artsy.net/other/purchase-request-icons.zip

**Comment by 1aurabrown** [comment]
@tayapage6 @anipetrov @alloy @briansw My proposal from sprint planning, to cut time, was to do this desktop-only (since that work is mostly done) rather than responsive. Thoughts?

**Comment by briansw** [comment]
>@tayapage6 @anipetrov @alloy @briansw My proposal from sprint planning, to cut time, was to do this desktop-only (since that work is mostly done) rather than responsive. Thoughts?

This seems fine to me, but @anipetrov should weigh in on how this would affect how much longer the test would need to run.

**Comment by anipetrov** [comment]
That would be fine, we just need to figure out the test specs

**Comment by 1aurabrown** [comment]
@briansw i think there are two more icons on the confirmation page that aren't in the zip

**Comment by briansw** [comment]
@1aurabrown ah sorry about that, here's the full set: http://files.artsy.net/other/purchase-request-icon-set.zip

**Comment by 1aurabrown** [comment]
@briansw thanks! I'm also having trouble finding that green check circle next to the confirmation message. 
I'm seeing only this one:
![screen shot 2016-12-01 at 3 04 36 pm](https://cloud.githubusercontent.com/assets/3171662/20796669/7d06da48-b7d7-11e6-8e76-8d590ceadeee.png)

**Comment by briansw** [comment]
Ah, thought that was in the font already. Here's that one too: http://files.artsy.net/images/green-check.svg

**Comment by 1aurabrown** [comment]
@briansw "Contact flow adjustment for users who aren't logged in" -> this seems unrelated to the purchase flow and the a/b test. wasn't this implemented for every user when the forced login test was closed? Or is this just a UI update to something that already exists?

**Comment by 1aurabrown** [comment]
closing as this has entered qa and there are new qa items for each issue that came up.

**Comment by anipetrov** [comment]
is this in staging now @1aurabrown?
