### ISSUE TITLE
Institutional profile page QA

### ISSUE THREAD

**Issue by garrengotthardt** [artsy/force#530]
@oxaudo @gnilekaw sorry this took me so long to get to the QA but here are a couple things i found

- [x] Works tab should not include for sale works per last two bullets here: https://github.com/artsy/force/issues/441

![screen shot 2016-12-13 at 10 11 42 am](https://cloud.githubusercontent.com/assets/1863593/21145572/c5a865e8-c11c-11e6-9636-895c3eefde93.png)

- [x] if artists tab is hidden via https://github.com/artsy/volt/issues/2280 so should artists section of the overview
![artistspagevsartistssection](https://cloud.githubusercontent.com/assets/1863593/21145697/2ec008d8-c11d-11e6-94b4-7361889b3f63.gif)

- [x] per second to last bullet here: https://github.com/artsy/force/issues/441 shop tab should only display if works count > 0
![screen shot 2016-12-13 at 10 40 50 am](https://cloud.githubusercontent.com/assets/1863593/21146736/bdf3143e-c120-11e6-9d34-bcbdb3dc3d0d.png)

- [x] selecting the banner style to display last updated works in volt seems to just remove the banner altogether:
![screen shot 2016-12-13 at 10 43 34 am](https://cloud.githubusercontent.com/assets/1863593/21146824/00efe0aa-c121-11e6-8f9e-ad5b11c44d95.png)
![screen shot 2016-12-13 at 10 42 39 am](https://cloud.githubusercontent.com/assets/1863593/21146826/02a359fe-c121-11e6-8d99-1489d37d2d06.png)

**Comment by gnilekaw** [comment]
Thanks! I got these.

**Comment by garrengotthardt** [comment]
@gnilekaw added one more

**Comment by garrengotthardt** [comment]
added another

**Comment by garrengotthardt** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Institutional Profile Page QA](https://trello.com/c/C9ryFX31/756-institutional-profile-page-qa)

**Comment by oxaudo** [comment]
@garrengotthardt - both the 3rd and 4th point above is a staging data issue. Thanks for detailed debugging @starsirius and @gnilekaw! Please check the same thing on production being logged in as admin and you should not see the correct data

**Comment by garrengotthardt** [comment]
great thanks @oxaudo !

**Comment by gnilekaw** [comment]
Update on showing only not-for-sale works in the Works view: This requires an update to one of Gravity's elastic queries. I have a PR submitted. Once that's up on Staging, there are a couple more updates here, and we should be good.

**Comment by gnilekaw** [comment]
The works view now shows only not-for-sale artworks, and the shop view shows only for-sale ones.

https://www.artsy.net/whitechapel-gallery/collection

https://www.artsy.net/whitechapel-gallery/shop?for_sale=true

**Comment by starsirius** [comment]
Closed via https://github.com/artsy/gravity/pull/10650, https://github.com/artsy/force/pull/581, https://github.com/artsy/force/pull/561, https://github.com/artsy/force/pull/451
